webapp/forms.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-03-15 23:27:56
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-08-29 10:24:53
#表单工具

from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, PasswordField, BooleanField,TextField,IntegerField,SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, URL,Email,NumberRange

from webapp.models import User

class CommentForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

class LoginForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(max=255, message=u'填写用户名')])
    password = PasswordField(u'密码',validators=[DataRequired(), Length(max=255, message=u'填写密码')])
    verification_code = StringField(u'验证码', validators=[DataRequired(), Length(4, 4, message=u'填写4位验证码')])
    remember = BooleanField("Remember Me")

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append(u'用户名或密码错误！')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append(u'用户名或密码错误！')
            return False

        return True

class PostForm(FlaskForm):
    title = StringField('Title', [DataRequired(), Length(max=255)])
    text = TextAreaField('Content', [DataRequired()])

class RegisterForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(max=255, message=u'填写用户名')])
    email = TextField(u'邮箱',validators=[DataRequired(), Length(max=255, message=u'填写邮件地址')])
    tel = StringField(u'手机号')
    password = PasswordField(u'密码', validators=[DataRequired(), Length(max=255, message=u'填写密码')])
    confirm = PasswordField(u'确认密码', validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('注册')

    #recaptcha = RecaptchaField()

    def validate(self):
        check_validate = super(RegisterForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()

        # Is the username already being used
        if user:
            self.username.errors.append(u"用户名已存在！")
            return False

        return True

webapp/__init__.py
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import os
from flask import Flask
from webapp.models import db
from controllers.cdn import cdn_blueprint
from controllers.main import main_blueprint
from webapp.extensions import bcrypt,login_manager,admin,rest_api,principals
from webapp.controllers.rest.post import DomainApi,ProjectApi,UserApi
from webapp.controllers.rest.auth import AuthApi
from webapp.models import User,Project,Domain,Charge_info,Charge_statics,Role
from webapp.controllers.admin import (
        CustomView,
        CustomModelView,
        CustomFileAdmin

    )
from flask_login import current_user
from flask_principal import identity_loaded, UserNeed, RoleNeed

def datetimeformat(value, format="%Y-%m"):
    return value.strftime(format)

def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)
    principals.init_app(app)


    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        # Set the identity user object
        identity.user = current_user
        print "In __init_.py......:%s" %current_user

        # Add the UserNeed to the identity
        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))
            print UserNeed(current_user.id)

        # Add each role to the identity
        if hasattr(current_user, 'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role.name))
                print RoleNeed(role.name)



    admin.add_view(CustomView(name='Custom'))

    models = [User,Project,Domain,Charge_info,Charge_statics,Role]
    for model in models:
        admin.add_view(
            CustomModelView(
                model,db.session,category='models'
                )
            )
    admin.add_view(
        CustomFileAdmin(
            os.path.join(os.path.dirname(__file__), 'static'),
            '/static/',
            name='Static Files'
        )
    )

    app.register_blueprint(cdn_blueprint)
    app.register_blueprint(main_blueprint)

    app.jinja_env.filters['datetimeformat'] = datetimeformat

    #解析类和对应的路由
    rest_api.add_resource(
    AuthApi,
    '/api/auth',
    )

    rest_api.add_resource(
        DomainApi,
        '/api/domain',
        '/api/domain/<int:domain_id>',
    )

    rest_api.add_resource(
        ProjectApi,
        '/api/project', #获取所有项目
        '/api/project/<int:project_id>/', #操作[查、改、删]某个项目
    )

    rest_api.add_resource(
        UserApi,
        '/api/user', #获取所有用户
        '/api/user/<int:user_id>', #操作[查、改、删]某个用户

    )

    rest_api.init_app(app)

    return app

if __name__ == '__main__':
    app = create_app('project.config.ProdConfig')
    app.run()

webapp/controllers/__init__.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-03-15 23:28:39
# @Last Modified by:   liuli
# @Last Modified time: 2017-03-15 23:54:58

webapp/controllers/admin.py
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_login import login_required, current_user

#from webapp.extensions import admin_permission
#from webapp.forms import CKTextAreaField


class CustomView(BaseView):
    @expose('/')
    @login_required
    #@admin_permission.require(http_exception=403)
    def index(self):
        return self.render('admin/custom.html')

    @expose('/second_page')
    @login_required
    #@admin_permission.require(http_exception=403)
    def second_page(self):
        return self.render('admin/second_page.html')


class CustomModelView(ModelView):
    def is_accessible(self):
        print current_user
        return current_user.is_authenticated()


class CustomFileAdmin(FileAdmin):
    def is_accessible(self):
        print current_user
        return current_user.is_authenticated()

webapp/controllers/cdn.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-03-15 23:28:39
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-10-31 12:01:06
import os,time
from os import path
import datetime,json
import csv
from StringIO import StringIO
from sqlalchemy import func
from flask import (render_template,
                   Blueprint,
                   redirect,
                   url_for,
                   abort,
                   flash,
                   request)
from flask_login import login_required, current_user
from flask_principal import Permission, UserNeed

from webapp.extensions import poster_permission, admin_permission

from webapp.models import db,User,Project,Charge_info,Charge_statics,Domain
from webapp.forms import CommentForm, PostForm
from ..utils import wangsustatics,fastwebstatics
from ..utils.pro import project_http,project_https,fastweb

cdn_blueprint = Blueprint(
    'cdn',
    __name__,
    template_folder=path.join(path.pardir,'templates','cdn'),
    url_prefix="/cdn"
    )


'''
处理时间不为json格式的问题
'''
class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj, date):
            return obj.strftime('%Y-%m-%d')
        else:
            return json.JSONEncoder.default(self, obj)

'''
自定义过滤器
'''
def dateformat(value, format="%Y-%m"):
    return value.strftime(format)


#download_type分为http和https两种
#download_domian分为project_http.domain和project_https.domain两种
#fastweb只有http一种类型，而wangsu有http和https两种类型
def insert_traffic_data(cname,year,month,download_type=None,download_domain=None):
    if cname =='fastweb':
        os.chdir('/usr/local/src/myproject/cdnadmin/webapp/utils')
        _rt_statics,total_money = fastwebstatics.get_statics_result(year,month)
        #print _rt_statics,total_money
    elif cname == 'wangsu' and download_type=='http':
        _rt_statics = wangsustatics.get_traffic_result(myflag=download_type,mydomain=project_http.domain,year=year,month=month)
    elif  cname == 'wangsu' and download_type=='https':
        _rt_statics = wangsustatics.get_traffic_result(myflag=download_type,mydomain=project_https.domain,year=year,month=month)

    for val in _rt_statics:
        new_comment = Charge_statics()
        new_comment.charge_date = datetime.datetime.now().strptime(val[0],"%Y-%m")
        new_comment.charge_cname = val[1]
        new_comment.charge_type = val[2]
        new_comment.charge_project = val[3]
        new_comment.charge_area = val[4]
        new_comment.charge_traff = val[5]
        new_comment.charge_total = val[6]
        new_comment.charge_percent = val[7]

        db.session.add(new_comment)
        db.session.commit()

def commit_date(domain_cname):
    new_domain = Domain()
    new_domain.cname = domain_cname
    new_domain.status = 1
    new_domain.purpose = ''
    new_domain.project_id = project_id
    new_domain.domain_name = v
    new_domain.end_date = datetime.datetime.now()+datetime.timedelta(1000)
    new_domain.start_date = datetime.datetime.now()-datetime.timedelta(1500)

    db.session.add(new_domain)
    db.session.commit()

def insert_domain(domain_cname):
    if domain_cname == 'fastweb':
        fastweb_dic = {'jx1':'剑一','jx3':'剑三','jxsj':'剑世','yy':'月影','fkxd':'反恐行动'}
        for k in fastweb.project:
            if k == 'all':continue
            project_id = Project.query.filter_by(project_name=fastweb_dic[k]).first().id
            for v in fastweb.project[k]:
                new_domain = Domain()
                new_domain.cname = '快网'
                new_domain.status = 1
                new_domain.purpose = '快网-HTTP下载加速'
                new_domain.project_id = project_id
                new_domain.domain_name = v
                new_domain.end_date = datetime.datetime.now()+datetime.timedelta(1000)
                new_domain.start_date = datetime.datetime.now()-datetime.timedelta(1500)

                db.session.add(new_domain)
                db.session.commit()
    elif domain_cname == 'wangsu_http':
        for k in project_http.domain:
            if k == 'all':continue
            project_id = Project.query.filter_by(project_name=k).first().id
            for v in project_http.domain[k]:
                new_domain = Domain()
                new_domain.cname = '网宿'
                new_domain.status = 1
                new_domain.purpose = '网宿-HTTP下载加速'
                new_domain.project_id = project_id
                new_domain.domain_name = v
                new_domain.end_date = datetime.datetime.now()+datetime.timedelta(1000)
                new_domain.start_date = datetime.datetime.now()-datetime.timedelta(1500)

                db.session.add(new_domain)
                db.session.commit()
    elif domain_cname == 'wangsu_https':
        for k in project_https.domain:
            if k == 'all':continue
            project_id = Project.query.filter_by(project_name=k).first().id
            for v in project_https.domain[k]:
                new_domain = Domain()
                new_domain.cname = '网宿'
                new_domain.status = 1
                new_domain.purpose = '网宿-HTTPS下载加速'
                new_domain.project_id = project_id
                new_domain.domain_name = v
                new_domain.end_date = datetime.datetime.now()+datetime.timedelta(1000)
                new_domain.start_date = datetime.datetime.now()-datetime.timedelta(1500)

                db.session.add(new_domain)
                db.session.commit()

def get_current_user():
    try:
        cur_user = current_user.username
    except Exception as e:
        flash(u"请先登录!")
        return  redirect(url_for('main.login'))
    else:
        user = User.query.filter_by(username=cur_user).one()
        return user

    #price=Charge_info.query.filter_by(nick_name='cn').filter_by(charge_cname='网宿').filter_by(charge_type='下载加速').all()[0].charge_price
    #return prices

@cdn_blueprint.route('/')
@login_required
def home():
    cur_user = get_current_user()
    year = datetime.date.today().year
    month = datetime.date.today().month-1
    charge_date = '%s-%s-01 00:00:00' %(year,month)
    print charge_date
    distinct_cname_list = db.session.query(func.distinct(Charge_statics.charge_cname)).all()
    #修改成只显示当月的数据-2017-10-31修改
    #charge_statics = db.session.query(Charge_statics.charge_date.label('charge_date'),Charge_statics.charge_project.label('charge_project'),func.sum(Charge_statics.charge_total)).group_by(Charge_statics.charge_project).all()
    charge_statics = db.session.query(Charge_statics.charge_date.label('charge_date'),Charge_statics.charge_project.label('charge_project'),func.sum(Charge_statics.charge_total)).filter_by(charge_date=charge_date).group_by(Charge_statics.charge_project).all()
    fa_list = ["fa fa-eye fa-2x","fa fa-shopping-cart fa-2x","fa fa-comments fa-2x","fa fa-users fa-2x","fa fa-bug fa-2x","fa fa-calendar fa-2x","fa fa-cloud-upload fa-2x","fa fa-cloud-download fa-2x"]
    fa_color = ["card-image red","card-image orange","card-image blue","card-image"]
    return render_template('dashboardtype.html',login_user=cur_user.username,charge_statics=charge_statics,fa_list=fa_list,fa_color=fa_color)

@cdn_blueprint.route('/logout/')
def logout():
    return  redirect(url_for('main.logout'))

@cdn_blueprint.route('/custom/')
@login_required
def custom():
    cur_user = get_current_user()
    permission = Permission(UserNeed(cur_user.id))
    #insert_traffic_data('wangsu',2017,11,download_type='http',download_domain=project_http.domain)
    #insert_traffic_data('wangsu',2017,11,download_type='https',download_domain=project_https.domain)
    #insert_traffic_data('fastweb',2017,11,download_type='http')
    #insert_domain('fastweb')
    return render_template('custom.html',login_user=cur_user.username,price='successed!')

@cdn_blueprint.route('/apiauth/')
@login_required
def apiauth():
    cur_user = get_current_user()
    return render_template('apiauth.html',login_user=cur_user.username,price='API使用说明!')

@cdn_blueprint.route('/apiproject/')
@login_required
def apiproject():
    cur_user = get_current_user()
    return render_template('apiproject.html',login_user=cur_user.username,price='API使用说明!')

@cdn_blueprint.route('/apidomain/')
@login_required
def apidomain():
    cur_user = get_current_user()
    return render_template('apidomain.html',login_user=cur_user.username,price='API使用说明!')

@cdn_blueprint.route('/dashboard/')
@login_required
def dashboard():
    cur_user = get_current_user()
    project_legend_fastweb,status_data_fastweb_5=Charge_statics.get_charge_statics(charge_date='2017-05-01 00:00:00',charge_cname='快网')
    project_legend_fastweb,status_data_fastweb_6=Charge_statics.get_charge_statics(charge_date='2017-06-01 00:00:00',charge_cname='快网')
    project_legend_wangsu,status_data_wangsu_5,project_legend_client_wangsu,status_data_wangsu_client_5,project_legend_phone_wangsu,status_data_wangsu_phone_5=Charge_statics.get_charge_statics(charge_date='2017-05-01 00:00:00',charge_cname='网宿')
    project_legend_wangsu,status_data_wangsu_6,project_legend_client_wangsu,status_data_wangsu_client_6,project_legend_phone_wangsu,status_data_wangsu_phone_6=Charge_statics.get_charge_statics(charge_date='2017-06-01 00:00:00',charge_cname='网宿')

    return render_template('dashboard.html',login_user=cur_user.username,
        project_legend_wangsu=json.dumps(project_legend_wangsu),
        status_data_wangsu_5=json.dumps(status_data_wangsu_5),status_data_wangsu_6=json.dumps(status_data_wangsu_6),
        project_client_wangsu=json.dumps(project_legend_client_wangsu),

webapp/controllers/rest/auth.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-04-05 22:14:45
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-08-08 21:41:23
from flask import abort, current_app
from flask_restful import Resource

from webapp.models import User
from webapp.controllers.rest.parsers import user_post_parser

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


class AuthApi(Resource):
    def post(self):
        args = user_post_parser.parse_args()
        user = User.query.filter_by(username=args['username']).one()

        if user.check_password(args['password']):
            s = Serializer(current_app.config['SECRET_KEY'], expires_in=604800)
            return {"token": s.dumps({'id': user.id})}
        else:
            abort(401)

webapp/templates/cdn/blank.html
{% extends "base.html" %}

{% block title %}blank page{% endblock %}

{% block currentpagename %}
Blank Pages
{% endblock %}

{% block content %}
	<table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
          <tr>
            <th>#</th>
            <th>CDN厂商</th>
            <th>下载地区</th>
            <th>地区简写</th>
            <th>计费类型</th>
            <th>单价(元/MB)</th>
          </tr>
        </thead>
        <tbody>

            <tr>
                <td>1</td>
                <td>11</td>
                <td>111</td>
                <td>1111</td>
                <td>11111</td>
                <td>111111</td>
            </tr>

        </tbody>
    </table>
{% endblock %}


webapp/templates/cdn/dashboard-backup.html
{% extends "layout.html" %}
{% block title %}CDN管理{% endblock %}
 {% block scripts %}
<script src="/static/assets/js/year_month_day.js"></script>
{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
 {% block topbutton %}waves-effect waves-dark{% endblock %}
 {% block loginuser %}{{login_user}}{% endblock %}
 {% block content %}
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
          <div class="header">
                        <h1 class="page-header">
                            Dashboard
                        </h1>
                        <ol class="breadcrumb">

                      <li><a href="{{url_for('cdn.dashboard') }}">Dashboard</a></li>
                      <li class="active">Data</li>
                    </ol>

        </div>


            <div id="page-inner">
                <div class="row" >
                    <div class="select-block">
                        <span class="title">选择年份:</span>
                        <select style="display:inline-block;width:90px" id="selYear"></select>

                        <span class="title">选择月份:</span>
                        <select style="display:inline-block;width:90px" id="selMonth"></select>
                    </div>

                        <script type="text/javascript">
                            var selYear = window.document.getElementById("selYear");
                            var selMonth = window.document.getElementById("selMonth");

                            new DateSelector(selYear, selMonth,  2017, 5);
                         </script>

                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-3">

                        <div class="card horizontal cardIcon waves-effect waves-dark">
                        <div class="card-image red">
                        <i class="fa fa-eye fa-5x"></i>
                        </div>
                        <div class="card-stacked">
                        <div class="card-content">
                        <h3><a href="{{url_for('cdn.custom') }}">16,150</a></h3>
                        </div>
                        <div class="card-action">
                        <strong> Daily Visits</strong>
                        </div>
                        </div>
                        </div>

                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-3">

                        <div class="card horizontal cardIcon waves-effect waves-dark">
                        <div class="card-image orange">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="card-stacked">
                        <div class="card-content">
                        <h3>25,550</h3>
                        </div>
                        <div class="card-action">
                        <strong> Sales</strong>
                        </div>
                        </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-3">

                            <div class="card horizontal cardIcon waves-effect waves-dark">
                        <div class="card-image blue">
                        <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="card-stacked">
                        <div class="card-content">
                        <h3>11,225</h3>
                        </div>
                        <div class="card-action">
                        <strong> Comments</strong>
                        </div>
                        </div>
                        </div>

                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-3">

                    <div class="card horizontal cardIcon waves-effect waves-dark">
                        <div class="card-image">
                        <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="card-stacked">
                        <div class="card-content">
                        <h3>72,525</h3>
                        </div>
                        <div class="card-action">
                        <strong> Visits</strong>
                        </div>
                        </div>
                        </div>

                    </div>
                </div>


           <footer><p>Copyright &copy; 2017.Company name All rights reserved.<a target="_blank" href="#"></a></p></footer>
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
   <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="/static/assets/js/jquery-1.10.2.js"></script>

    <!-- Bootstrap Js -->
    <script src="/static/assets/js/bootstrap.min.js"></script>

    <script src="/static/assets/materialize/js/materialize.min.js"></script>

    <!-- Metis Menu Js -->
    <script src="/static/assets/js/jquery.metisMenu.js"></script>
    <!-- Morris Chart Js -->
    <script src="/static/assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="/static/assets/js/morris/morris.js"></script>


    <!--script src="/static/assets/js/easypiechart.js"></script>
    <script src="/static/assets/js/easypiechart-data.js"></script-->

     <script src="/static/assets/js/Lightweight-Chart/jquery.chart.js"></script>

    <!-- Custom Js -->
    <script src="/static/assets/js/custom-scripts.js"></script>

    <script type="text/javascript">
        {% block js %}
        $("document").ready(function() {

             $('select').change(function() {
                var year=jQuery('#selYear').val();
                var month=jQuery('#selMonth').val();
                //console.log(year,month);

            var params = {};
            params['year'] = jQuery('#selYear').val();
            params['month'] = jQuery('#selMonth').val();
            window.location.replace('{{url_for('cdn.dashboard')}}'+year+'/'+month+'/');
       })

   });


        {% endblock %}
    </script>

{% endblock %}


webapp/templates/cdn/layout.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
{% block head %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="/static/temp/favicon.ico">
    <!-- Bootstrap Styles-->
    <link href="/static/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="/static/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="/static/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="/static/assets/css/custom-styles.css" rel="stylesheet" />
    <!-- Google Fonts-->
   <link href="/static/css/fonts.googleapis.com.css"  rel='stylesheet' type='text/css' />
    {% block link %}{% endblock %}
    <style type="text/css">
        {% block style %}{% endblock %}
    </style>
    <!-- JS Scripts block-->
    {% block scripts %}{% endblock %}
{% endblock %}
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('cdn.home') }}"><i class="fa fa-comments"></i> <strong>CDN管理</strong></a>
                <div id="sideNav" style="background-color:#1cc09f"><i class="fa fa-outdent" ></i></div>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                        <i class="fa fa-user fa-fw"></i>{% block loginuser %}{% endblock %}<i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{url_for('cdn.userinfo')}}"><i class="fa fa-user fa-fw"></i>个人信息</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i>用户设置</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{url_for('.logout')}}"><i class="fa fa-sign-out fa-fw"></i>登出</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a href="{{url_for('cdn.dashboard') }}" class="{% block dashboardisactive %}{% endblock %}"><i class="fa fa-dashboard"></i> Dashboard</a>
                    </li>

                    <li>
                        <a href="{{url_for('cdn.tables') }}" class="{% block tablesisactive %}{% endblock %}"><i class="fa fa-table"></i>CDN费用详表</a>
                    </li>
                     <li>
                        <a href="{{url_for('cdn.tablestotal') }}" class="{% block tablestotalisactive %}{% endblock %}"><i class="fa fa-desktop"></i>CDN费用汇总</a>
                    </li>

                     <li>
                        <a href="#" class="{% block domainprojectisactive %}{% endblock %}"><i class="fa fa-sitemap"></i>配置管理<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{url_for('cdn.domainadmin') }}">域名管理</a>
                            </li>
                            <li>
                                <a href="{{url_for('cdn.projectadmin') }}">项目管理</a>
                            </li>
                             <li>
                                <a href="{{url_for('cdn.priceinfo') }}">CDN价格表</a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a href="#" class="{% block apiisactive %}{% endblock %}"><i class="fa fa-tasks"></i>API使用说明<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{url_for('cdn.apiauth') }}">认证接口API</a>
                            </li>
                            <li>
                                <a href="{{url_for('cdn.apiproject') }}">项目管理API</a>
                            </li>
                             <li>
                                <a href="{{url_for('cdn.apidomain') }}">域名管理API</a>
                            </li>

                        </ul>
                    </li>


                     <li>
                        <a class="{% block customisactive %}{% endblock %}" href="{{url_for('cdn.custom') }}"><i class="fa fa-fw fa-file"></i>自定义
                        </a>
                    </li>
                </ul>

            </div>

        </nav>

    </div>

    {% block content %}{% endblock %}
    <!-- JS Scripts block-->
    {% block script %}{% endblock %}

    <script type="text/javascript">
    {% block js %}{% endblock %}
    </script>
</body>

</html>