webapp/forms.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-03-15 23:27:56
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-08-29 10:24:53
#表单工具

from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, PasswordField, BooleanField,TextField,IntegerField,SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, URL,Email,NumberRange

from webapp.models import User

class CommentForm(FlaskForm):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

class LoginForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(max=255, message=u'填写用户名')])
    password = PasswordField(u'密码',validators=[DataRequired(), Length(max=255, message=u'填写密码')])
    verification_code = StringField(u'验证码', validators=[DataRequired(), Length(4, 4, message=u'填写4位验证码')])
    remember = BooleanField("Remember Me")

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append(u'用户名或密码错误！')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append(u'用户名或密码错误！')
            return False

        return True

class PostForm(FlaskForm):
    title = StringField('Title', [DataRequired(), Length(max=255)])
    text = TextAreaField('Content', [DataRequired()])

class RegisterForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired(), Length(max=255, message=u'填写用户名')])
    email = TextField(u'邮箱',validators=[DataRequired(), Length(max=255, message=u'填写邮件地址')])
    tel = StringField(u'手机号')
    password = PasswordField(u'密码', validators=[DataRequired(), Length(max=255, message=u'填写密码')])
    confirm = PasswordField(u'确认密码', validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('注册')

    #recaptcha = RecaptchaField()

    def validate(self):
        check_validate = super(RegisterForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()

        # Is the username already being used
        if user:
            self.username.errors.append(u"用户名已存在！")
            return False

        return True

webapp/__init__.py
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import os
from flask import Flask
from webapp.models import db
from controllers.cdn import cdn_blueprint
from controllers.main import main_blueprint
from webapp.extensions import bcrypt,login_manager,admin,rest_api,principals
from webapp.controllers.rest.post import DomainApi,ProjectApi,UserApi
from webapp.controllers.rest.auth import AuthApi
from webapp.models import User,Project,Domain,Charge_info,Charge_statics,Role
from webapp.controllers.admin import (
        CustomView,
        CustomModelView,
        CustomFileAdmin

    )
from flask_login import current_user
from flask_principal import identity_loaded, UserNeed, RoleNeed

def datetimeformat(value, format="%Y-%m"):
    return value.strftime(format)

def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)
    principals.init_app(app)


    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        # Set the identity user object
        identity.user = current_user
        print "In __init_.py......:%s" %current_user

        # Add the UserNeed to the identity
        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))
            print UserNeed(current_user.id)

        # Add each role to the identity
        if hasattr(current_user, 'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role.name))
                print RoleNeed(role.name)



    admin.add_view(CustomView(name='Custom'))

    models = [User,Project,Domain,Charge_info,Charge_statics,Role]
    for model in models:
        admin.add_view(
            CustomModelView(
                model,db.session,category='models'
                )
            )
    admin.add_view(
        CustomFileAdmin(
            os.path.join(os.path.dirname(__file__), 'static'),
            '/static/',
            name='Static Files'
        )
    )

    app.register_blueprint(cdn_blueprint)
    app.register_blueprint(main_blueprint)

    app.jinja_env.filters['datetimeformat'] = datetimeformat

    #解析类和对应的路由
    rest_api.add_resource(
    AuthApi,
    '/api/auth',
    )

    rest_api.add_resource(
        DomainApi,
        '/api/domain',
        '/api/domain/<int:domain_id>',
    )

    rest_api.add_resource(
        ProjectApi,
        '/api/project', #获取所有项目
        '/api/project/<int:project_id>/', #操作[查、改、删]某个项目
    )

    rest_api.add_resource(
        UserApi,
        '/api/user', #获取所有用户
        '/api/user/<int:user_id>', #操作[查、改、删]某个用户

    )

    rest_api.init_app(app)

    return app

if __name__ == '__main__':
    app = create_app('project.config.ProdConfig')
    app.run()

webapp/controllers/__init__.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-03-15 23:28:39
# @Last Modified by:   liuli
# @Last Modified time: 2017-03-15 23:54:58

webapp/controllers/admin.py
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_login import login_required, current_user

#from webapp.extensions import admin_permission
#from webapp.forms import CKTextAreaField


class CustomView(BaseView):
    @expose('/')
    @login_required
    #@admin_permission.require(http_exception=403)
    def index(self):
        return self.render('admin/custom.html')

    @expose('/second_page')
    @login_required
    #@admin_permission.require(http_exception=403)
    def second_page(self):
        return self.render('admin/second_page.html')


class CustomModelView(ModelView):
    def is_accessible(self):
        print current_user
        return current_user.is_authenticated()


class CustomFileAdmin(FileAdmin):
    def is_accessible(self):
        print current_user
        return current_user.is_authenticated()

webapp/controllers/main.py
# -*- coding: utf-8 -*-
# @Author: XUEQUN
# @Date:   2017-03-17 11:16:27
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-09-28 10:10:40

from flask import (render_template,
                   current_app,
                   Blueprint,
                   redirect,
                   url_for,
                   request,
                   flash,
                   session,
                   make_response)
from flask_principal import (
    Identity,
    AnonymousIdentity,
    identity_changed
)
from webapp.forms import LoginForm, RegisterForm
from os import path
from webapp.models import User,db
from flask_login import login_user, logout_user
import random
from PIL import Image, ImageDraw, ImageFont, ImageFilter
import StringIO
import string,random


main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder=path.join(path.pardir,'templates','main'),
    )

#生成验证码图片
#numbers = ''.join(map(str, range(10)))
numbers = string.digits+string.letters
chars = ''.join((numbers))


def create_validate_code(size=(120, 30),
                         chars=chars,
                         mode="RGB",
                         bg_color=(255, 255, 255),
                         fg_color=(255, 0, 0),
                         font_size=18,
                         font_type="/usr/local/src/myproject/cdnadmin/webapp/static/temp/stkaiti.ttf",
                         length=4,
                         draw_points=True,
                         point_chance = 2):
    '''''
    size: 图片的大小，格式（宽，高），默认为(120, 30)
    chars: 允许的字符集合，格式字符串
    mode: 图片模式，默认为RGB
    bg_color: 背景颜色，默认为白色
    fg_color: 前景色，验证码字符颜色
    font_size: 验证码字体大小
    font_type: 验证码字体，默认为 stkaiti.ttf
    length: 验证码字符个数
    draw_points: 是否画干扰点
    point_chance: 干扰点出现的概率，大小范围[0, 50]
    '''

    width, height = size
    img = Image.new(mode, size, bg_color) # 创建图形
    draw = ImageDraw.Draw(img) # 创建画笔

    def get_chars():
        '''''生成给定长度的字符串，返回列表格式'''
        return random.sample(chars, length)

    def create_points():
        '''''绘制干扰点'''
        chance = min(50, max(0, int(point_chance))) # 大小限制在[0, 50]

        for w in xrange(width):
            for h in xrange(height):
                tmp = random.randint(0, 50)
                if tmp > 50 - chance:
                    draw.point((w, h), fill=(0, 0, 0))

    def create_strs():
        '''''绘制验证码字符'''
        c_chars = get_chars()
        strs = '%s' % ''.join(c_chars)

        font = ImageFont.truetype(font_type, font_size)
        font_width, font_height = font.getsize(strs)

        draw.text(((width - font_width) / 3, (height - font_height) / 4),
                    strs, font=font, fill=fg_color)

        return strs

    if draw_points:
        create_points()
    strs = create_strs()

    # 图形扭曲参数
    """
    params = [1 - float(random.randint(1, 2)) / 100,
              0,
              0,
              0,
              1 - float(random.randint(1, 10)) / 100,
              float(random.randint(1, 2)) / 500,
              0.001,
              float(random.randint(1, 2)) / 500
              ]
    img = img.transform(size, Image.PERSPECTIVE, params) # 创建扭曲
   """
    img = img.filter(ImageFilter.EDGE_ENHANCE_MORE) # 滤镜，边界加强（阈值更大）

    #image保存到内存中
    buf = StringIO.StringIO()
    img.save(buf,'JPEG',quality=70)

    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'

    return response,strs

@main_blueprint.route('/')
def index():
    return redirect(url_for('main.login'))

@main_blueprint.route('/login', methods=['GET', 'POST'])
#@oid.loginhandler
def login():
    form = LoginForm()
    print 'In form %s' %(form.verification_code.data)
    print 'In session %s' %(session.get('code'))
    #获取表单里面输入的数据
    form_code = form.verification_code.data
    #获取session中的数字
    session_code = session.get('code')
    #openid_form = OpenIDForm()

    # if openid_form.validate_on_submit():
    #     return oid.try_login(
    #         openid_form.openid.data,
    #         ask_for=['nickname', 'email'],
    #         ask_for_optional=['fullcmd

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user, remember=form.remember.data)

        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.id)
        )
        if form_code != session_code:
            form.verification_code.errors.append(u'验证码错误，请重新输入！')
        else:

        #flash("You have been logged in.", category="success")
            return redirect(url_for('cdn.home'))

    # openid_errors = oid.fetch_error()
    # if openid_errors:
    #     flash(openid_errors, category="danger")

    #return render_template('login.html', form=form, openid_form=openid_form)
    return render_template('login.html', form=form)


@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    session.clear()
    logout_user()

    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )

    flash(u"成功退出!", category="success")
    return redirect(url_for('.login'))


@main_blueprint.route('/register', methods=['GET', 'POST'])
#@oid.loginhandler
def register():
    form = RegisterForm()
    # openid_form = OpenIDForm()

    # if openid_form.validate_on_submit():
    #     return oid.try_login(
    #         openid_form.openid.data,
    #         ask_for=['nickname', 'email'],
    #         ask_for_optional=['fullname']
    #     )

    if form.validate_on_submit():
        new_user = User(form.username.data)
        new_user.email = form.email.data
        new_user.tel = form.tel.data
        new_user.status = 0
        new_user.set_password(form.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash(u"用户创建成功，请登陆.", category="success")

        return redirect(url_for('.login'))

    # openid_errors = oid.fetch_error()
    # if openid_errors:
    #     flash(openid_errors, category="danger")

    #return render_template('register.html', form=form, openid_form=openid_form)
    return render_template('register.html', form=form)



@main_blueprint.route('/code/')
def get_code():
    #把strs发给前端,或者在后台使用session保存
    #返回图片和上面的文字
    response,strs = create_validate_code()
    #保存文字到session
    session['code'] = strs
    #image保存到内存中
    #buf = StringIO.StringIO()
    #code_img.save(buf,'JPEG',quality=70)

    #buf_str = buf.getvalue()
    #response = make_response(buf_str)
    #response.headers['Content-Type'] = 'image/jpeg'
    return response

webapp/controllers/rest/auth.py
# -*- coding: utf-8 -*-
# @Author: liuli
# @Date:   2017-04-05 22:14:45
# @Last Modified by:   XUEQUN
# @Last Modified time: 2017-08-08 21:41:23
from flask import abort, current_app
from flask_restful import Resource

from webapp.models import User
from webapp.controllers.rest.parsers import user_post_parser

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


class AuthApi(Resource):
    def post(self):
        args = user_post_parser.parse_args()
        user = User.query.filter_by(username=args['username']).one()

        if user.check_password(args['password']):
            s = Serializer(current_app.config['SECRET_KEY'], expires_in=604800)
            return {"token": s.dumps({'id': user.id})}
        else:
            abort(401)

webapp/templates/main/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Home{% endblock %}</title>
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
        <link rel="stylesheet" type='text/css' media='screen' href="{{url_for('static',filename='css/signup.css')}}">
        <link rel="stylesheet" type='text/css' media='screen' href="{{url_for('static',filename='css/signin.css')}}">
        <style type="text/css">
            {% block style %}{% endblock %}
        </style>
    </head>
    <body background="static/img/bgs/landscape.jpg">
        <div class="container">
            <!--div class="jumbotron">
                <h1><a href="{{ url_for('main.login') }}">CDN-Admin</a></h1>
                <p>Welcome to the cdn system!</p>
            </div-->

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}

            {% endblock %}
        </div>
        <script type="text/javascript" src="{{url_for('static', filename='jquery/jquery-1.11.2.min.js')}}" ></script>
         <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}" ></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

webapp/templates/main/login.html
{% extends "main/base.html" %}
{% block title %}用户登录{% endblock %}
{% block style %}
  .box {margin-top:100px;}
{% endblock %}
{% block body %}

 <div class="row">
 <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="row-fluid login-wrapper">
        <!--h2>CDN管理系统</h2-->
        <div class="box">
            <div class="content-wrap">
            <h3 class="text-center">用户登录</h3>
            <form method="POST" action="{{ url_for('.login') }}">
                {{ form.hidden_tag() }}

                <div class="form-group" >

                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class="form-control", required=True) }}
                </div>

                <div class="form-group">

                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class="form-control", required=True) }}
                </div>


                 <div class="form-group">
                    {{ form.verification_code.label }}
                    {% if form.verification_code.errors %}
                        {% for e in form.verification_code.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    <label class="control-label"><img src="{{ url_for('main.get_code')}}"  onclick="this.src='./code?d='+Math.random();"></label>
                    {{ form.verification_code(class="form-control", required=True) }}
                </div>

                <input class="btn btn-info" style="width: 100%;" type="submit" value="登录">
            </form>
            </div>
        </div>
        <hr/>
        <div class="register">
         <a type="button" class="btn btn-info" style="width: 100%;" href="register">没有账号？注册</a>
     </div>
    </div>
    </div>
    </div>

{% endblock %}

webapp/templates/main/register.html
{% extends "main/base.html" %}
{% block title %}用户注册{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="text-center">用户注册</h1>
             <form method="POST" action="{{ url_for('.register') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class="form-control", required=True) }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class="form-control", required=True) }}
                </div>
                <div class="form-group">
                    {{ form.confirm.label }}
                    {% if form.confirm.errors %}
                        {% for e in form.confirm.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.confirm(class="form-control", required=True) }}
                </div>

                <div class="form-group">
                    {{ form.tel.label }}
                    {% if form.tel.errors %}
                        {% for e in form.tel.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.tel(class="form-control", required=True) }}
                </div>

                <div class="form-group">
                    {{ form.email.label }}
                    {% if form.email.errors %}
                        {% for e in form.email.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.email(class="form-control", required=True) }}
                </div>

                <!--input class="btn btn-primary" type="submit" value="Register"   {{ form.submit(class="btn btn-info submit") }}-->
                 <input class="btn btn-info" style="width: 100%;" type="submit" value="注册">

            </form>
            <hr/>
            <div class="register">
                 <a type="button" class="btn btn-info" style="width: 100%;" href="login">已有账号？登录</a>
             </div>

        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}